/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GlobalHeader {
    }
    interface InputForm {
    }
    interface MainApp {
    }
    interface TodoItems {
        "index": number;
        "onComplete": (index: number, completed: boolean) => void;
        "onDelete": (index: number) => void;
        "todo": Todo;
    }
    interface TodoList {
    }
}
export interface InputFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLInputFormElement;
}
declare global {
    interface HTMLGlobalHeaderElement extends Components.GlobalHeader, HTMLStencilElement {
    }
    var HTMLGlobalHeaderElement: {
        prototype: HTMLGlobalHeaderElement;
        new (): HTMLGlobalHeaderElement;
    };
    interface HTMLInputFormElement extends Components.InputForm, HTMLStencilElement {
    }
    var HTMLInputFormElement: {
        prototype: HTMLInputFormElement;
        new (): HTMLInputFormElement;
    };
    interface HTMLMainAppElement extends Components.MainApp, HTMLStencilElement {
    }
    var HTMLMainAppElement: {
        prototype: HTMLMainAppElement;
        new (): HTMLMainAppElement;
    };
    interface HTMLTodoItemsElement extends Components.TodoItems, HTMLStencilElement {
    }
    var HTMLTodoItemsElement: {
        prototype: HTMLTodoItemsElement;
        new (): HTMLTodoItemsElement;
    };
    interface HTMLTodoListElement extends Components.TodoList, HTMLStencilElement {
    }
    var HTMLTodoListElement: {
        prototype: HTMLTodoListElement;
        new (): HTMLTodoListElement;
    };
    interface HTMLElementTagNameMap {
        "global-header": HTMLGlobalHeaderElement;
        "input-form": HTMLInputFormElement;
        "main-app": HTMLMainAppElement;
        "todo-items": HTMLTodoItemsElement;
        "todo-list": HTMLTodoListElement;
    }
}
declare namespace LocalJSX {
    interface GlobalHeader {
    }
    interface InputForm {
        "onTodoAdded"?: (event: InputFormCustomEvent<string>) => void;
    }
    interface MainApp {
    }
    interface TodoItems {
        "index"?: number;
        "onComplete"?: (index: number, completed: boolean) => void;
        "onDelete"?: (index: number) => void;
        "todo"?: Todo;
    }
    interface TodoList {
    }
    interface IntrinsicElements {
        "global-header": GlobalHeader;
        "input-form": InputForm;
        "main-app": MainApp;
        "todo-items": TodoItems;
        "todo-list": TodoList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "global-header": LocalJSX.GlobalHeader & JSXBase.HTMLAttributes<HTMLGlobalHeaderElement>;
            "input-form": LocalJSX.InputForm & JSXBase.HTMLAttributes<HTMLInputFormElement>;
            "main-app": LocalJSX.MainApp & JSXBase.HTMLAttributes<HTMLMainAppElement>;
            "todo-items": LocalJSX.TodoItems & JSXBase.HTMLAttributes<HTMLTodoItemsElement>;
            "todo-list": LocalJSX.TodoList & JSXBase.HTMLAttributes<HTMLTodoListElement>;
        }
    }
}
